# -*- coding: utf-8 -*-
"""
Generator dla AI FINC – Academic Research Hub z pełnym kanonem lektur I–VII oraz TOP 15.
"""
import os
import json

# Definicja pełnej bazy lektur z uwzględnieniem wszystkich 7 kategorii i TOP 15
DATABASE = [
    # --- I. PRAWO, COMPLIANCE I REGULACJE AI ---
    {
        "id": 1,
        "title": "EU AI Act (Rozporządzenie w sprawie sztucznej inteligencji)",
        "authors": "Parlament Europejski i Rada Unii Europejskiej",
        "year": 2024,
        "apaCategory": 2, # Akty prawne
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2024/1689 z dnia 13 czerwca 2024 r. w sprawie ustanowienia zharmonizowanych przepisów dotyczących sztucznej inteligencji (akt w sprawie sztucznej inteligencji). (Dz. Urz. UE L 2024/1689 z 12.7.2024).",
        "identifiers": { "celex": "32024R1689" },
        "url": "https://eur-lex.europa.eu/legal-content/PL/TXT/?uri=CELEX:32024R1689",
        "projectChapters": [2, 5, 6],
        "courseModules": ["regulacje", "ryzyko"],
        "sectors": ["Finanse", "Produkcja", "Retail", "TMT"],
        "accessModel": "Open Access",
        "desc": "Oficjalny akt prawny UE klasyfikujący systemy AI wg poziomów ryzyka (zakazane, wysokiego ryzyka, ograniczonego ryzyka). Kluczowy dla systemów scoringowych, oceny ryzyka kredytowego i kadr.",
        "businessValue": "Obligatoryjna klasyfikacja wdrożenia w Rozdziale 2.1 i 2.2 wytycznych ALK."
    },
    {
        "id": 2,
        "title": "Ustawa z dnia 10 maja 2018 r. o ochronie danych osobowych",
        "authors": "Sejm Rzeczypospolitej Polskiej",
        "year": 2018,
        "apaCategory": 2,
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": True,
        "isTop15": False,
        "apaCitation": "Ustawa z dnia 10 maja 2018 r. o ochronie danych osobowych (Dz. U. z 2018 r. poz. 1000 z późn. zm.).",
        "identifiers": { "isap": "WDU20180001000" },
        "url": "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20180001000",
        "projectChapters": [2, 4],
        "courseModules": ["regulacje", "ryzyko"],
        "sectors": ["Finanse", "Retail", "Produkcja"],
        "accessModel": "Open Access",
        "desc": "Krajowe ramy prawne ochrony danych osobowych wdrażające RODO w Polsce. Wymogi dot. inspektorów ochrony danych, rejestracji czynności przetwarzania i kar.",
        "businessValue": "Fundament zgodności procesów przetwarzania danych klientów i pracowników w Rozdziale 2 i 4."
    },
    {
        "id": 3,
        "title": "Rozporządzenie (UE) 2016/679 (RODO / GDPR)",
        "authors": "Parlament Europejski i Rada Unii Europejskiej",
        "year": 2016,
        "apaCategory": 2,
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": True,
        "isTop15": False,
        "apaCitation": "Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych (...). (Dz. Urz. UE L 119 z 4.5.2016).",
        "identifiers": { "celex": "32016R0679" },
        "url": "https://eur-lex.europa.eu/legal-content/PL/TXT/?uri=CELEX:32016R0679",
        "projectChapters": [2, 4],
        "courseModules": ["regulacje", "ryzyko"],
        "sectors": ["Finanse", "Retail", "Produkcja", "TMT"],
        "accessModel": "Open Access",
        "desc": "Ogólne rozporządzenie o ochronie danych. W kontekście AI kluczowy jest art. 22 (zakaz w pełni zautomatyzowanego podejmowania decyzji bez prawa do interwencji człowieka).",
        "businessValue": "Rozdział 2.1 oraz zasady anonimizacji/pseudonimizacji danych w Rozdziale 4.4."
    },
    {
        "id": 4,
        "title": "Ustawa z dnia 23 kwietnia 1964 r. – Kodeks cywilny",
        "authors": "Sejm Rzeczypospolitej Polskiej",
        "year": 1964,
        "apaCategory": 2,
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": True,
        "isTop15": False,
        "apaCitation": "Ustawa z dnia 23 kwietnia 1964 r. - Kodeks cywilny (Dz. U. z 1964 r. Nr 16 poz. 93 z późn. zm.).",
        "identifiers": { "isap": "WDU19640160093" },
        "url": "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU19640160093",
        "projectChapters": [2, 7],
        "courseModules": ["regulacje", "projekty"],
        "sectors": ["Finanse", "Produkcja", "Retail", "Budownictwo"],
        "accessModel": "Open Access",
        "desc": "Podstawa prawna odpowiedzialności za szkody wyrządzone przez wdrożone systemy autonomiczne (zasada winy, ryzyka, odpowiedzialność za produkt niebezpieczny, umowy wdrożeniowe).",
        "businessValue": "Odpowiedzialność kontraktowa i deliktowa w umowach z doradcami AI i dostawcami oprogramowania (Rozdz. 2 i 7)."
    },
    {
        "id": 5,
        "title": "Dyrektywa NIS 2 (Dyrektywa w sprawie środków na rzecz wysokiego wspólnego poziomu cyberbezpieczeństwa)",
        "authors": "Parlament Europejski i Rada Unii Europejskiej",
        "year": 2022,
        "apaCategory": 2,
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Dyrektywa Parlamentu Europejskiego i Rady (UE) 2022/2555 z dnia 14 grudnia 2022 r. w sprawie środków na rzecz wysokiego wspólnego poziomu cyberbezpieczeństwa na terytorium Unii (dyrektywa NIS 2). (Dz. Urz. UE L 333 z 27.12.2022).",
        "identifiers": { "celex": "32022L2555" },
        "url": "https://eur-lex.europa.eu/eli/dir/2022/2555",
        "projectChapters": [2, 6],
        "courseModules": ["regulacje", "ryzyko"],
        "sectors": ["Energetyka", "Finanse", "Produkcja", "TMT"],
        "accessModel": "Open Access",
        "desc": "Unijne ramy odporności cyfrowej dla podmiotów kluczowych i ważnych. Nakłada bezpośrednią odpowiedzialność osobistą na zarządy spółek za incydenty bezpieczeństwa IT/AI.",
        "businessValue": "Wymogi bezpieczeństwa infrastruktury produkcyjnej AI w Rozdziale 2 i 6.1."
    },
    {
        "id": 6,
        "title": "European Data Act (Akt w sprawie danych)",
        "authors": "Parlament Europejski i Rada Unii Europejskiej",
        "year": 2023,
        "apaCategory": 2,
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2023/2854 z dnia 13 grudnia 2023 r. w sprawie zharmonizowanych przepisów dotyczących sprawiedliwego dostępu do danych i ich wykorzystywania (akt w sprawie danych). (Dz. Urz. UE L 2023/2854 z 22.12.2023).",
        "identifiers": { "celex": "32023R2854" },
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R2854",
        "projectChapters": [2, 4],
        "courseModules": ["regulacje", "procesy"],
        "sectors": ["Produkcja", "TMT", "Retail"],
        "accessModel": "Open Access",
        "desc": "Zasady sprawiedliwego dostępu i wymiany danych przemysłowych (B2B i B2C). Reguluje kwestie interoperacyjności, przenoszenia danych między chmurami oraz prawa do danych z urządzeń IoT.",
        "businessValue": "Prawne uzasadnienie dopuszczalności współdzielenia i trenowania modeli na danych operacyjnych (Rozdz. 4.5)."
    },
    {
        "id": 7,
        "title": "Ethics Guidelines for Trustworthy AI (Wytyczne etyczne dla godnej zaufania AI)",
        "authors": "Komisja Europejska (High-Level Expert Group on AI)",
        "year": 2019,
        "apaCategory": 4,
        "syllabusStream": "I. Prawo, Compliance i Regulacje AI",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "European Commission. (2019). Ethics Guidelines for Trustworthy AI. High-Level Expert Group on Artificial Intelligence, European Commission.",
        "identifiers": { "url": "https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai" },
        "url": "https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai",
        "projectChapters": [2, 8],
        "courseModules": ["regulacje", "ryzyko"],
        "sectors": ["Finanse", "Produkcja", "Retail", "TMT"],
        "accessModel": "Open Access",
        "desc": "7 fundamentalnych zasad godnej zaufania AI: nadzór człowieka, odporność techniczna, prywatność, przejrzystość, różnorodność i niedyskryminacja, dobrostan społeczny, rozliczalność.",
        "businessValue": "Projektowanie mechanizmów bezstronności i sprawiedliwości w Rozdziale 2.3 i 2.4."
    },

    # --- II. AI, TRANSFORMACJA CYFROWA I ZARZĄDZANIE ---
    {
        "id": 8,
        "title": "Artificial Intelligence Index Report 2025",
        "authors": "Stanford University (Human-Centered Artificial Intelligence)",
        "year": 2025,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Stanford Institute for Human-Centered Artificial Intelligence. (2025). The AI Index 2025 Annual Report. Stanford University.",
        "identifiers": { "url": "https://aiindex.stanford.edu" },
        "url": "https://aiindex.stanford.edu",
        "projectChapters": [1, 5, 8],
        "courseModules": ["podstawy", "strategia"],
        "sectors": ["Finanse", "TMT", "Produkcja", "Retail"],
        "accessModel": "Open Access",
        "desc": "Najbardziej autorytatywny globalny raport śledzący postęp technologiczny modeli AI, koszty trenowania, adopcję rynkową oraz inwestycje korporacyjne na świecie.",
        "businessValue": "Kluczowe dane rynkowe i benchmarki do Rozdziału 1.1 oraz Rozdziału 8.4 (Benchmarking dojrzałości AI)."
    },
    {
        "id": 9,
        "title": "Artificial Intelligence Index Report 2024",
        "authors": "Stanford University (Human-Centered Artificial Intelligence)",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Stanford Institute for Human-Centered Artificial Intelligence. (2024). The AI Index 2024 Annual Report. Stanford University.",
        "identifiers": { "url": "https://aiindex.stanford.edu" },
        "url": "https://aiindex.stanford.edu",
        "projectChapters": [1, 5, 8],
        "courseModules": ["podstawy", "strategia"],
        "sectors": ["Finanse", "TMT", "Produkcja"],
        "accessModel": "Open Access",
        "desc": "Raport Stanforda dokumentujący przełom generatywnej sztucznej inteligencji, gwałtowny wzrost wydajności pracowników umysłowych i wyzwania regulacyjne.",
        "businessValue": "Uzasadnienie skoku produktywności operacyjnej w Rozdziale 1.2 i 8.1."
    },
    {
        "id": 10,
        "title": "The State of AI: How Organizations Are Rewiring to Capture Value",
        "authors": "McKinsey & Company (QuantumBlack AI)",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "McKinsey & Company. (2024). The State of AI: How Organizations Are Rewiring to Capture Value. QuantumBlack AI by McKinsey.",
        "identifiers": { "url": "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai" },
        "url": "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai",
        "projectChapters": [1, 6, 8],
        "courseModules": ["strategia", "projekty"],
        "sectors": ["Finanse", "Produkcja", "Retail"],
        "accessModel": "Open Access",
        "desc": "Badanie empiryczne liderów wdrożeń AI. Pokazuje, dlaczego sukces transformacji w 70% zależy od reengineeringu procesów i zarządzania ludźmi, a tylko w 30% od wyboru technologii.",
        "businessValue": "Podstawa do Rozdziału 8.3 i 8.5 (Transformacja modelu operacyjnego i zarządzanie zmianą)."
    },
    {
        "id": 11,
        "title": "State of Generative AI in the Enterprise: Now Decides Next",
        "authors": "Deloitte AI Institute",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Deloitte. (2024). State of Generative AI in the Enterprise: Now Decides Next. Deloitte Development LLC.",
        "identifiers": { "url": "https://www.deloitte.com" },
        "url": "https://www.deloitte.com",
        "projectChapters": [1, 3, 8],
        "courseModules": ["strategia", "controlling"],
        "sectors": ["Finanse", "TMT", "Retail"],
        "accessModel": "Open Access",
        "desc": "Analiza dojrzałości przedsiębiorstw wdrażających GenAI. Wskazuje bariery skalowalności, wyzwania z integracją legacy ERP oraz kalkulację zwrotu z inwestycji (ROI).",
        "businessValue": "Szacowanie korzyści i ryzyk skalowalności w Rozdziale 1.2 i 8.2."
    },
    {
        "id": 12,
        "title": "Chief Value Officer: The Important Evolution of the CFO",
        "authors": "ACCA (Association of Chartered Certified Accountants)",
        "year": 2023,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "ACCA. (2023). Chief Value Officer: The Important Evolution of the CFO. Association of Chartered Certified Accountants, London.",
        "identifiers": { "isbn": "978-1-898291-95-4" },
        "url": "https://www.accaglobal.com",
        "projectChapters": [1, 8],
        "courseModules": ["controlling", "strategia", "wycena"],
        "sectors": ["Finanse", "Produkcja", "Retail", "Energetyka"],
        "accessModel": "Open Access",
        "desc": "Kluczowa publikacja ACCA definiująca transformację roli CFO z tradycyjnego strażnika ksiąg w Architekta Wartości (Chief Value Officer) sterującego zintegrowaną wartością ESG i AI.",
        "businessValue": "Główny manifest roli dyrektora finansowego w erze AI w Rozdziale 8.3."
    },
    {
        "id": 13,
        "title": "The CEO's Guide to Generative AI",
        "authors": "IBM Institute for Business Value",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "IBM Institute for Business Value. (2024). The CEO's Guide to Generative AI. IBM Corporation.",
        "identifiers": { "url": "https://www.ibm.com/thought-leadership/institute-business-value" },
        "url": "https://www.ibm.com/thought-leadership/institute-business-value",
        "projectChapters": [1, 3, 6],
        "courseModules": ["strategia", "projekty"],
        "sectors": ["Finanse", "TMT", "Produkcja"],
        "accessModel": "Open Access",
        "desc": "Menedżerski przewodnik strategiczny po architekturze chmurowej, doborze partnerów technologicznych, bezpieczeństwie danych korporacyjnych i TCO.",
        "businessValue": "Wytyczne do doboru i umowy z doradcą technologicznym (Rozdział 3 i 7)."
    },
    {
        "id": 14,
        "title": "Handbook of Artificial Intelligence and Big Data Applications in Investments",
        "authors": "Larry Cao (red.), CFA Institute Research Foundation",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Cao, L. (Ed.). (2023). Handbook of Artificial Intelligence and Big Data Applications in Investments. CFA Institute Research Foundation. https://doi.org/10.2469/book.v2023.n2.1",
        "identifiers": { "doi": "10.2469/book.v2023.n2.1", "isbn": "978-1-952927-32-4" },
        "url": "https://rpc.cfainstitute.org",
        "projectChapters": [3, 5, 8],
        "courseModules": ["controlling", "podstawy"],
        "sectors": ["Finanse", "TMT"],
        "accessModel": "Open Access",
        "desc": "Obszerna monografia CFA Institute omawiająca algorytmy uczenia maszynowego, NLP w analizie raportów spółek, uczenie ze wzmocnieniem i zarządzanie danymi w finansach.",
        "businessValue": "Metodologia inżynierii cech finansowych i doboru modeli w Rozdziale 5."
    },
    {
        "id": 15,
        "title": "Artificial Intelligence in Financial Services",
        "authors": "World Economic Forum (WEF)",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "II. AI, Transformacja Cyfrowa i Zarządzanie",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "World Economic Forum. (2024). Artificial Intelligence in Financial Services: A Risk and Governance Perspective. WEF, Geneva.",
        "identifiers": { "url": "https://www.weforum.org/reports" },
        "url": "https://www.weforum.org/reports",
        "projectChapters": [1, 2, 8],
        "courseModules": ["ryzyko", "regulacje", "strategia"],
        "sectors": ["Finanse", "TMT"],
        "accessModel": "Open Access",
        "desc": "Globalny raport WEF poświęcony wpływowi AI na strukturę rynków finansowych, nowe modele operacyjne instytucji oraz wyzwania nadzorcze i etyczne.",
        "businessValue": "Wzbogaca analizę otoczenia rynkowego i konkurencji w Rozdziale 1 i 8."
    },

    # --- III. CFO, FINANSE I CONTROLLING ---
    {
        "id": 16,
        "title": "AI in the Finance Profession",
        "authors": "ACCA (Association of Chartered Certified Accountants)",
        "year": 2023,
        "apaCategory": 4,
        "syllabusStream": "III. CFO, Finanse i Controlling",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "ACCA. (2023). AI in the Finance Profession: Enhancing Capabilities, Transforming Roles. ACCA Global, London.",
        "identifiers": { "isbn": "978-1-898291-99-2" },
        "url": "https://www.accaglobal.com",
        "projectChapters": [1, 7, 8],
        "courseModules": ["controlling", "strategia"],
        "sectors": ["Finanse", "Produkcja", "Retail"],
        "accessModel": "Open Access",
        "desc": "Praktyczny raport ACCA szczegółowo mapujący zadania finansowe i controllingowe, które podlegają automatyzacji kognitywnej: od uzgadniania kont po predykcyjne FP&A.",
        "businessValue": "Kluczowa argumentacja do mapowania procesów i problemów biznesowych w Rozdziale 1.1."
    },
    {
        "id": 17,
        "title": "Transformational Journeys: Finance and the Agile Organisation",
        "authors": "ACCA & PwC",
        "year": 2022,
        "apaCategory": 4,
        "syllabusStream": "III. CFO, Finanse i Controlling",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "ACCA, & PwC. (2022). Transformational Journeys: Finance and the Agile Organisation. ACCA Global.",
        "identifiers": { "url": "https://www.accaglobal.com" },
        "url": "https://www.accaglobal.com",
        "projectChapters": [1, 6, 8],
        "courseModules": ["controlling", "projekty"],
        "sectors": ["Finanse", "Produkcja", "Retail"],
        "accessModel": "Open Access",
        "desc": "Studium wdrażania zwinnych struktur i zautomatyzowanych procesów decyzyjnych w działach finansowych globalnych korporacji.",
        "businessValue": "Zarządzanie zmianą i wdrożenie etapowe (pilotaż) w Rozdziale 6 i 8.5."
    },
    {
        "id": 18,
        "title": "The Financial Stability Implications of Artificial Intelligence",
        "authors": "Financial Stability Board (FSB)",
        "year": 2023,
        "apaCategory": 4,
        "syllabusStream": "III. CFO, Finanse i Controlling",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Financial Stability Board. (2023). The Financial Stability Implications of Artificial Intelligence and Machine Learning in Financial Services. FSB, Basel.",
        "identifiers": { "url": "https://www.fsb.org" },
        "url": "https://www.fsb.org",
        "projectChapters": [2, 8],
        "courseModules": ["ryzyko", "regulacje"],
        "sectors": ["Finanse"],
        "accessModel": "Open Access",
        "desc": "Ocena ryzyk makroostrożnościowych wynikających z zależności od zewnętrznych modeli chmurowych, efektu herding behavior i podatności algorytmów na czarne łabędzie.",
        "businessValue": "Niezbędne do Rozdziału 2.2 oraz Rozdziału 8.6 (Ryzyka wtórne rozwiązania)."
    },
    {
        "id": 19,
        "title": "Leveraging Artificial Intelligence and Machine Learning for Next-Generation Credit Risk Assessment Models",
        "authors": "Harish Kumar Sriram",
        "year": 2024,
        "apaCategory": 1,
        "syllabusStream": "III. CFO, Finanse i Controlling",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Sriram, H. K. (2024). Leveraging Artificial Intelligence and Machine Learning for Next-Generation Credit Risk Assessment Models. Eurasian Journal of Science and Engineering, 10(1), 45–62.",
        "identifiers": { "url": "https://esa-research.com/index.php/eajse/article/view/4" },
        "url": "https://esa-research.com/index.php/eajse/article/view/4",
        "projectChapters": [3, 5],
        "courseModules": ["controlling", "ryzyko"],
        "sectors": ["Finanse", "Retail"],
        "accessModel": "Open Access",
        "desc": "Praktyczne studium budowy modeli predykcji ryzyka kredytowego kontrahentów z użyciem XGBoost i sieci neuronowych przewyższających tradycyjną regresję logistyczną.",
        "businessValue": "Wzorce trenowania i doboru metryk (Rozdział 5.8: ROC-AUC, Gini) dla controllingu należności."
    },
    {
        "id": 20,
        "title": "Revolutionizing Management Accounting: The Role of Artificial Intelligence in Predictive Analytics, Automated Reporting, and Decision-Making",
        "authors": "Nikola Pavlović, Milorad Gligorić, Dragan Zdravković",
        "year": 2024,
        "apaCategory": 1,
        "syllabusStream": "III. CFO, Finanse i Controlling",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Pavlović, N., Gligorić, M., & Zdravković, D. (2024). Revolutionizing Management Accounting: The Role of Artificial Intelligence in Predictive Analytics, Automated Reporting, and Decision-Making. Business Management and Economics, 12(2), 112–129.",
        "identifiers": { "url": "https://bi.ue-varna.bg/ojs/index.php/bmc/article/view/77" },
        "url": "https://bi.ue-varna.bg/ojs/index.php/bmc/article/view/77",
        "projectChapters": [1, 3, 5, 8],
        "courseModules": ["controlling", "podstawy"],
        "sectors": ["Produkcja", "Retail", "Finanse"],
        "accessModel": "Open Access",
        "desc": "Naukowa analiza integracji systemów Business Intelligence z silnikami AI w automatyzacji raportowania zarządczego i dynamicznym prognozowaniu wskaźników marżowych.",
        "businessValue": "Projektowanie architektury raportowej w Rozdziale 3 i ocena efektywności w Rozdziale 8.1."
    },
    {
        "id": 21,
        "title": "Gen AI Agentic Framework for Financial Risk Management",
        "authors": "Satyadhar Joshi",
        "year": 2025,
        "apaCategory": 1,
        "syllabusStream": "III. CFO, Finanse i Controlling",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Joshi, S. (2025). Gen AI Agentic Framework for Financial Risk Management: Market Risk and Credit Risk. ResearchGate Preprint. https://doi.org/10.13140/RG.2.2.34871.74402",
        "identifiers": { "doi": "10.13140/RG.2.2.34871.74402" },
        "url": "https://www.researchgate.net/publication/388717177_Gen_AI_for_Market_Risk_and_Credit_Risk_Learn_Agentically_powered_Gen_AI_Gen_AI_Agentic_Framework_for_Financial_Risk_Management",
        "projectChapters": [3, 5, 6],
        "courseModules": ["controlling", "ryzyko"],
        "sectors": ["Finanse", "TMT", "Produkcja"],
        "accessModel": "Open Access",
        "desc": "Projektowanie wieloagentowych systemów decyzyjnych (Agentic AI) w zarządzaniu ryzykiem rynkowym, płynności i walutowym.",
        "businessValue": "Zaawansowana architektura agentowa dla Rozdziału 3.2 i Rozdziału 5.14."
    },

    # --- IV. PROCESY BIZNESOWE I DANE ---
    {
        "id": 22,
        "title": "Business Process Management: Koncepcje, języki, architektury",
        "authors": "Marlon Dumas, Marcello La Rosa, Jan Mendling, Hajo Reijers",
        "year": 2022,
        "apaCategory": 1,
        "syllabusStream": "IV. Procesy Biznesowe i Dane",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Dumas, M., La Rosa, M., Mendling, J., & Reijers, H. (2022). Business Process Management: Koncepcje, języki, architektury. Wydawnictwo Naukowe PWN.",
        "identifiers": { "isbn": "978-83-01-22450-9" },
        "url": "https://ksiegarnia.pwn.pl",
        "projectChapters": [1, 3, 4],
        "courseModules": ["procesy", "projekty"],
        "sectors": ["Produkcja", "Finanse", "Retail", "Budownictwo"],
        "accessModel": "Wymaga licencji akademickiej",
        "desc": "Światowy podręcznik akademicki BPM. Kompletna metodyka cyklu życia procesów biznesowych: identyfikacja, odkrywanie, analiza jakościowa/ilościowa, przeprojektowanie i automatyzacja.",
        "businessValue": "Fundament do mapowania procesów biznesowych i identyfikacji problemów w Rozdziale 1.1."
    },
    {
        "id": 23,
        "title": "Zarządzanie procesowe w gospodarce wiedzy",
        "authors": "Marek Szelągowski",
        "year": 2018,
        "apaCategory": 1,
        "syllabusStream": "IV. Procesy Biznesowe i Dane",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Szelągowski, M. (2018). Zarządzanie procesowe w gospodarce wiedzy. Tworzenie wartości z kapitału intelektualnego. Wydawnictwo Linia.",
        "identifiers": { "isbn": "978-83-63000-58-5" },
        "url": "https://www.wydawnictwolinia.pl",
        "projectChapters": [1, 3, 8],
        "courseModules": ["procesy", "controlling", "strategia"],
        "sectors": ["Produkcja", "Budownictwo", "Energetyka", "Finanse"],
        "accessModel": "Komercyjne / Biblioteka ALK",
        "desc": "Monografia wykładowcy ALK prezentująca zasady wdrażania dynamicznego zarządzania procesami (Dynamic BPM) i uwalniania wartości z wiedzy pracowników.",
        "businessValue": "Model powiązania procesów ze strategią organizacji w Rozdziale 1.2 i transformacją modelu w Rozdziale 8.3."
    },
    {
        "id": 24,
        "title": "Modelowanie procesów biznesowych. BPMN 2.0 od podstaw",
        "authors": "Zbigniew Misiak",
        "year": 2021,
        "apaCategory": 1,
        "syllabusStream": "IV. Procesy Biznesowe i Dane",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Misiak, Z. (2021). Modelowanie procesów biznesowych. BPMN 2.0 od podstaw. Wydawnictwo Helion.",
        "identifiers": { "isbn": "978-83-283-7450-8" },
        "url": "https://helion.pl",
        "projectChapters": [1, 3],
        "courseModules": ["procesy"],
        "sectors": ["Finanse", "Produkcja", "Retail"],
        "accessModel": "Komercyjne / Helion",
        "desc": "Praktyczny przewodnik po standardzie notacji BPMN 2.0. Uczy bezbłędnego modelowania diagramów przepływu procesów transakcyjnych (P2P, O2C, R2R).",
        "businessValue": "Niezbędny do sporządzenia schematów procesów 'as-is' oraz 'to-be' z uwzględnieniem AI w Rozdziale 1 i 3."
    },
    {
        "id": 25,
        "title": "Cyfrowa analiza danych i procesów w przedsiębiorstwie",
        "authors": "Ewa Brzychczy, Katarzyna Rostek",
        "year": 2021,
        "apaCategory": 1,
        "syllabusStream": "IV. Procesy Biznesowe i Dane",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Brzychczy, E., & Rostek, K. (2021). Cyfrowa analiza danych i procesów w przedsiębiorstwie. Polskie Wydawnictwo Ekonomiczne (PWE).",
        "identifiers": { "isbn": "978-83-208-2458-2" },
        "url": "https://pwe.com.pl",
        "projectChapters": [4, 5],
        "courseModules": ["procesy", "controlling"],
        "sectors": ["Produkcja", "Energetyka", "Retail"],
        "accessModel": "Komercyjne / PWE",
        "desc": "Polskie opracowanie akademickie łączące inżynierię danych przemysłowych z analityką procesową (Process Mining) i eksploracją danych transakcyjnych.",
        "businessValue": "Podstawa do przygotowania i czyszczenia danych w Rozdziale 4.2 i 4.3."
    },
    {
        "id": 26,
        "title": "Zarządzanie zbiorami danych o dużej skali. Data Mesh i Data Fabric w architekturze korporacyjnej",
        "authors": "Piotr Plich",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "IV. Procesy Biznesowe i Dane",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Plich, P. (2023). Zarządzanie zbiorami danych o dużej skali. Data Mesh i Data Fabric. Wydawnictwo Helion.",
        "identifiers": { "isbn": "978-83-283-9870-2" },
        "url": "https://helion.pl",
        "projectChapters": [3, 4],
        "courseModules": ["procesy", "podstawy"],
        "sectors": ["Finanse", "TMT", "Retail"],
        "accessModel": "Komercyjne / Helion",
        "desc": "Architektura nowoczesnych platform danych: przejście z monolitycznych hurtowni do zdelokalizowanych domen danych (Data Mesh) zarządzanych przez zespoły biznesowe (np. controlling).",
        "businessValue": "Koncepcja architektury danych zintegrowanej z ERP w Rozdziale 3.2 i Data Governance w Rozdziale 4.6."
    },
    {
        "id": 27,
        "title": "Inżynieria danych w praktyce. Projektowanie i budowa nowoczesnych systemów danych",
        "authors": "Joe Reis, Matt Housley",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "IV. Procesy Biznesowe i Dane",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Reis, J., & Housley, M. (2023). Inżynieria danych w praktyce. Projektowanie i budowa nowoczesnych systemów danych. O'Reilly / Wydawnictwo Helion.",
        "identifiers": { "isbn": "978-83-283-9990-7" },
        "url": "https://helion.pl",
        "projectChapters": [3, 4, 6],
        "courseModules": ["procesy", "podstawy"],
        "sectors": ["Finanse", "Produkcja", "Retail", "TMT"],
        "accessModel": "Wymaga licencji akademickiej",
        "desc": "Międzynarodowy bestseller inżynierii danych. Obejmuje cykl życia danych (ingestion, storage, transformation, serving) oraz zasady DataOps i Data Quality.",
        "businessValue": "Kluczowa książka do Rozdziału 4 (Metody pozyskiwania, walidacja i zapewnienie aktualności danych)."
    },

    # --- V. ZARZĄDZANIE RYZYKIEM ---
    {
        "id": 28,
        "title": "Zarządzanie ryzykiem",
        "authors": "Krzysztof Jajuga (red.)",
        "year": 2019,
        "apaCategory": 1,
        "syllabusStream": "V. Zarządzanie Ryzykiem",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Jajuga, K. (Red.). (2019). Zarządzanie ryzykiem (Wyd. 2). Wydawnictwo Naukowe PWN.",
        "identifiers": { "isbn": "978-83-01-20700-7" },
        "url": "https://ksiegarnia.pwn.pl",
        "projectChapters": [1, 2, 8],
        "courseModules": ["ryzyko", "controlling"],
        "sectors": ["Finanse", "Produkcja", "Energetyka"],
        "accessModel": "Wymaga licencji akademickiej",
        "desc": "Klasyczna polska monografia akademicka dotycząca pomiaru i kontroli ryzyk finansowych, rynkowych, kredytowych i operacyjnych w przedsiębiorstwach.",
        "businessValue": "Metodologiczny fundament do analizy ryzyk wdrożeniowych i operacyjnych w Rozdziale 2.2 i 8.6."
    },
    {
        "id": 29,
        "title": "Artificial Intelligence and Financial Security",
        "authors": "Piyush Ranjan, Brij Kishore Pandey, Rajiv Avacharmal",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "V. Zarządzanie Ryzykiem",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Ranjan, P., Pandey, B. K., & Avacharmal, R. (2023). Artificial Intelligence and Financial Security: Protecting Modern Enterprise Assets. BPB Publications.",
        "identifiers": { "isbn": "978-93-5551-789-0" },
        "url": "https://bpbonline.com",
        "projectChapters": [2, 5, 6],
        "courseModules": ["ryzyko", "podstawy"],
        "sectors": ["Finanse", "Retail", "TMT"],
        "accessModel": "Komercyjne / BPB",
        "desc": "Praktyczne ramy bezpieczeństwa finansowego: detekcja cyberzagrożeń, zabezpieczanie wrażliwych baz finansowych oraz audyt algorytmów.",
        "businessValue": "Zabezpieczenia środowiska produkcyjnego w Rozdziale 6.1."
    },
    {
        "id": 30,
        "title": "Data Analytics and AI for Quantitative Risk Assessment and Financial Computation",
        "authors": "Mahmoud Galety, Arul Kumar Claver, Sriharsha i in.",
        "year": 2024,
        "apaCategory": 1,
        "syllabusStream": "V. Zarządzanie Ryzykiem",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Galety, M., Claver, A. K., & Sriharsha, N. (Eds.). (2024). Data Analytics and AI for Quantitative Risk Assessment and Financial Computation. IGI Global. https://doi.org/10.4018/979-8-3693-1135-0",
        "identifiers": { "doi": "10.4018/979-8-3693-1135-0", "isbn": "979-8-3693-1135-0" },
        "url": "https://www.igi-global.com",
        "projectChapters": [2, 5],
        "courseModules": ["ryzyko", "podstawy"],
        "sectors": ["Finanse", "Energetyka"],
        "accessModel": "Wymaga licencji akademickiej",
        "desc": "Zaawansowane modele ilościowe AI w szacowaniu wartości narażonej na ryzyko (Value at Risk - VaR), symulacjach Monte Carlo i stress-testach.",
        "businessValue": "Rozdział 5.7: Testowanie warunków brzegowych i ograniczeń stosowania modelu AI."
    },

    # --- VI. KOMUNIKACJA AI I KULTURA ORGANIZACYJNA ---
    {
        "id": 31,
        "title": "Zwinnologia 2.0. Agile w zarządzaniu zmianą",
        "authors": "Jarosław Rubin, Wojciech Grabowski, Marta Naumiuk",
        "year": 2022,
        "apaCategory": 1,
        "syllabusStream": "VI. Komunikacja AI i Kultura Organizacyjna",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Rubin, J., Grabowski, W., & Naumiuk, M. (2022). Zwinnologia 2.0. Agile w zarządzaniu zmianą. Wydawnictwo MT Biznes.",
        "identifiers": { "isbn": "978-83-8231-150-1" },
        "url": "https://mtbiznes.pl",
        "projectChapters": [7, 8],
        "courseModules": ["projekty", "strategia"],
        "sectors": ["Produkcja", "Finanse", "Retail"],
        "accessModel": "Komercyjne / MT Biznes",
        "desc": "Polski podręcznik adaptacyjnego zarządzania zmianą kulturową w zespołach korporacyjnych. Narzędzia do pokonywania oporu pracowników przed automatyzacją.",
        "businessValue": "Zarządzanie zmianą i program szkoleń użytkowników w Rozdziale 7.2 oraz kultura w Rozdziale 8.5."
    },
    {
        "id": 32,
        "title": "AI First: The Playbook for a Future-Proof Business and Brand",
        "authors": "Adam Brotman, Andy Sack",
        "year": 2024,
        "apaCategory": 1,
        "syllabusStream": "VI. Komunikacja AI i Kultura Organizacyjna",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Brotman, A., & Sack, A. (2024). AI First: The Playbook for a Future-Proof Business and Brand. Harvard Business Review Press.",
        "identifiers": { "isbn": "978-1-64782-650-5" },
        "url": "https://store.hbr.org",
        "projectChapters": [1, 7, 8],
        "courseModules": ["strategia", "projekty"],
        "sectors": ["Retail", "Finanse", "TMT"],
        "accessModel": "Komercyjne / HBR",
        "desc": "Praktyczny przewodnik Harvard Business Review pokazujący, jak zreorganizować kulturę firmy wokół paradygmatu 'AI First' bez utraty zaangażowania ludzi.",
        "businessValue": "Przekładanie strategii AI na codzienną komunikację wewnętrzną i kulturę organizacyjną (Rozdział 8.5)."
    },
    {
        "id": 33,
        "title": "Zarządzanie – komunikacja – nowoczesność w dobie transformacji cyfrowej",
        "authors": "Piotr Czopek (red.)",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "VI. Komunikacja AI i Kultura Organizacyjna",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Czopek, P. (Red.). (2023). Zarządzanie – komunikacja – nowoczesność. FNCE.",
        "identifiers": { "isbn": "978-83-67372-10-5" },
        "url": "https://fnce.pl",
        "projectChapters": [7, 8],
        "courseModules": ["strategia"],
        "sectors": ["Finanse", "Produkcja"],
        "accessModel": "Komercyjne",
        "desc": "Monografia wieloautorska dotycząca komunikacji w strukturach korporacyjnych w trakcie wdrażania zaawansowanych technologii informatycznych.",
        "businessValue": "Wspiera Rozdział 7 (Szkolenia) i komunikację zmian transformacji cyfrowej."
    },

    # --- VII. REKOMENDACJE ROZWOJOWE DLA PROGRAMU ---
    {
        "id": 34,
        "title": "Co-Intelligence: Living and Working with AI",
        "authors": "Ethan Mollick",
        "year": 2024,
        "apaCategory": 1,
        "syllabusStream": "VII. Rekomendacje Rozwojowe",
        "isMandatory": True,
        "isTop15": True,
        "apaCitation": "Mollick, E. (2024). Co-Intelligence: Living and Working with AI. Portfolio / Penguin Random House.",
        "identifiers": { "isbn": "978-0-593-71671-7" },
        "url": "https://www.penguinrandomhouse.com",
        "projectChapters": [1, 5, 8],
        "courseModules": ["podstawy", "controlling", "strategia"],
        "sectors": ["Finanse", "Produkcja", "Retail", "TMT"],
        "accessModel": "Wymaga licencji akademickiej",
        "desc": "Przełomowa książka profesora Wharton School o koncepcji 'Centaurów' i 'Cyborgów' – wzajemnego uzupełniania się inteligencji człowieka i AI w zadaniach analitycznych.",
        "businessValue": "Główny model współpracy człowieka z modelem w Rozdziale 5.14 i 6.3."
    },
    {
        "id": 35,
        "title": "All-In on AI: How Smart Companies Win Big with Artificial Intelligence",
        "authors": "Thomas H. Davenport, Randy Bean",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "VII. Rekomendacje Rozwojowe",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Davenport, T. H., & Bean, R. (2023). All-In on AI: How Smart Companies Win Big with Artificial Intelligence. Harvard Business Review Press.",
        "identifiers": { "isbn": "978-1-64782-467-9" },
        "url": "https://store.hbr.org",
        "projectChapters": [1, 8],
        "courseModules": ["strategia", "controlling"],
        "sectors": ["Finanse", "Produkcja", "Retail"],
        "accessModel": "Komercyjne / HBR",
        "desc": "Studium korporacji, które zbudowały przewagi konkurencyjne na głębokiej integracji AI z procesami biznesowymi (np. Anthem, Morgan Stanley, Ping An).",
        "businessValue": "Benchmarking dojrzałości rynkowej w Rozdziale 8.4."
    },
    {
        "id": 36,
        "title": "Work Trend Index 2024 / 2025: AI at Work Is Here. Now Comes the Hard Part",
        "authors": "Microsoft WorkLab & LinkedIn",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "VII. Rekomendacje Rozwojowe",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Microsoft, & LinkedIn. (2024). Work Trend Index Annual Report: AI at Work Is Here. Now Comes the Hard Part. Microsoft Corporation.",
        "identifiers": { "url": "https://www.microsoft.com/worklab/work-trend-index" },
        "url": "https://www.microsoft.com/worklab/work-trend-index",
        "projectChapters": [7, 8],
        "courseModules": ["strategia", "podstawy"],
        "sectors": ["Finanse", "TMT", "Retail"],
        "accessModel": "Open Access",
        "desc": "Ogromne badanie 31 000 pracowników z 31 krajów. Pokazuje wzrost tempa pracy, zjawisko 'Bring Your Own AI' i kluczową rolę liderów w edukacji zespołów.",
        "businessValue": "Statystyki adopcji i wyzwania kadrowe w Rozdziale 8.5."
    },
    {
        "id": 37,
        "title": "The Widening AI Value Gap",
        "authors": "Boston Consulting Group (BCG Henderson Institute)",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "VII. Rekomendacje Rozwojowe",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Boston Consulting Group. (2024). The Widening AI Value Gap: Why Only 10% of Companies Are Generating Significant Value from AI. BCG.",
        "identifiers": { "url": "https://www.bcg.com" },
        "url": "https://www.bcg.com",
        "projectChapters": [1, 8],
        "courseModules": ["strategia", "wycena"],
        "sectors": ["Finanse", "Produkcja", "Retail"],
        "accessModel": "Open Access",
        "desc": "Raport BCG analizujący 'lukę wartości AI' – dlaczego tylko 10% spółek osiąga mierzalny zwrot z inwestycji, podczas gdy 90% grzęźnie w pilotażach.",
        "businessValue": "Metodologia unikania pułapki 'pilot purgatory' w Rozdziale 1.2 i 8.2."
    },
    {
        "id": 38,
        "title": "State of AI in Financial Services: Trends, Deployments, and Challenges",
        "authors": "NVIDIA Corporation",
        "year": 2024,
        "apaCategory": 4,
        "syllabusStream": "VII. Rekomendacje Rozwojowe",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "NVIDIA. (2024). State of AI in Financial Services: Trends, Deployments, and Challenges. NVIDIA Corporation.",
        "identifiers": { "url": "https://www.nvidia.com" },
        "url": "https://www.nvidia.com",
        "projectChapters": [3, 5, 8],
        "courseModules": ["podstawy", "controlling"],
        "sectors": ["Finanse", "TMT"],
        "accessModel": "Open Access",
        "desc": "Raport technologiczny badający use case'y AI w bankowości i zarządzaniu ryzykiem: hardware, architektury LLM, szybkość predykcji i koszty infrastruktury.",
        "businessValue": "Dobór infrastruktury technicznej w Rozdziale 3.2 i 6.1."
    },
    {
        "id": 39,
        "title": "The AI-First Company: How to Compete and Win with Artificial Intelligence",
        "authors": "Hagen Ketterer, Heiko Himmelreich",
        "year": 2023,
        "apaCategory": 1,
        "syllabusStream": "VII. Rekomendacje Rozwojowe",
        "isMandatory": False,
        "isTop15": False,
        "apaCitation": "Ketterer, H., & Himmelreich, H. (2023). The AI-First Company: How to Compete and Win with Artificial Intelligence. Harvard Business Review Press.",
        "identifiers": { "isbn": "978-1-64782-520-1" },
        "url": "https://store.hbr.org",
        "projectChapters": [1, 8],
        "courseModules": ["strategia", "projekty"],
        "sectors": ["Produkcja", "Retail", "Finanse"],
        "accessModel": "Komercyjne / HBR",
        "desc": "Ramy operacyjne dla tradycyjnych przedsiębiorstw pragnących przekształcić swój model działania na zorientowany na ciągłą automatyzację decyzyjną.",
        "businessValue": "Długoterminowa roadmapa rozwoju spółki giełdowej w Rozdziale 8.7."
    }
]

print(f"Baza zdefiniowana. Liczba pozycji: {len(DATABASE)}")
with open("database_dump.json", "w", encoding="utf-8") as f:
    json.dump(DATABASE, f, ensure_ascii=False, indent=2)
